### ISSUE TITLE
jeparse exit abnormally

### ISSUE THREAD

**Issue by ddwolf** [CENSUS/shadow#18]
I am using the commit `c54da79f2ab5215901ee3b3c7e804802e2ef4c79` and it failed like this:
```
[shadow] parsing structures from memory...
[shadow] 2021-11-03 18:13:59
[shadow] error: cannot evaluate arenas[0]
Python Exception <type 'exceptions.SystemExit'> <type 'exceptions.SystemExit'>: 
Error occurred in Python command: <type 'exceptions.SystemExit'>
```

if I use the latest version then it complained: `Error occurred in Python command: No symbol "arena_bin_t" in current context`

the jemalloc I am using is `5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756`

**Comment by aristos-d** [comment]
This is unfortunately expected behavior. The tool was originally developed with jemalloc version 4.x in mind. With the release of version 5, the layout of the used data structures changed significantly. "arena_bin_t" is a name of a data structure in version 4. It is replaced in version 5 by the structure "bin_t" with a similar (not identical) function. There was some effort to port the tool to version 5 and Android 10 but it is far from complete. The relevant code is on the android10 branch.

**Comment by ddwolf** [comment]
thanks for your kindly reply, I will try other ways to debug my programe:)
