### ISSUE TITLE
how to create the cfg file 

### ISSUE THREAD

**Issue by jinyu00** [CENSUS/shadow#9]
I am debuging on android 5.1.0. how can i create the cfg for my device

**Comment by vats-** [comment]
Hi jinyu00,

shadow currently supports Android versions **>= 6**. 

Adding support for Android 5 is not just a matter of creating a cfg file as there are
changes between the two jemalloc versions that have to be handled in shadow's code.

For now, you'll have to update your device in order to use shadow.
